
CREATE TABLE IF NOT EXISTS StorageBatteryMeasurement();
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS activePower decimal;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS areaServed path;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS batteryAssessmentMethods text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS batteryLevel jsonb;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS batteryStatus text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS current decimal;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS dateEnergyMeteringStarted text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS dateObserved text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS dateObservedFrom text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS dateObservedTo text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS deepOfDischarge decimal;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS inverterStatus jsonb;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS openCircuitVoltage decimal;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS reactivePower decimal;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS refPointOfInterest jsonb;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS refStorageBatteryDevice jsonb;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS seeAlso jsonb;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS stateOfCharge decimal;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS stateOfHealth decimal;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS temperature decimal;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE StorageBatteryMeasurement ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeDeleted boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS SimulationReport();
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS smartTrafficLightKey bigint references SmartTrafficLight(pk);
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS simulationName text;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS smartTrafficLightId text;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS smartTrafficLightName text;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramAvgVehiclePerMinFromWestToEast decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramAvgVehiclePerMinFromSouthToNorth decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramVehicleDemandScalingFactor decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramAvgPedestrianPerMinFromWestToEast decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramAvgPedestrianPerMinFromSouthToNorth decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramPedestrianDemandScalingFactor decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramMinGreenTimeSecWestEast decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramMaxGreenTimeSecWestEast decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramMinGreenTimeSecSouthNorth decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramMaxGreenTimeSecSouthNorth decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramPedestrianWaitThresholdSecNorthSouth decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramPedestrianWaitThresholdSecWestEast decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramVehicleQueueThresholdWestEast decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramVehicleQueueThresholdSouthNorth decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramPedestrianQueueThresholdNorthSouth decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramPedestrianQueueThresholdWestEast decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramDemandScale decimal[];
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramStepSize decimal;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramRunTime integer;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramItersPerPar integer;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS paramTotalIterNum integer;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS updatedParameters jsonb;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS updatedPerformance jsonb;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS averageQueueLength jsonb;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS reportStatus text;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS reportProgress integer;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS reportName text;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS simulationKey bigint references TrafficSimulation(pk);
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SimulationReport ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS TrafficSimulation();
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS startDateTime timestamp with time zone;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS simulationName text;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS entityId text;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS sumocfgPath text;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS fcdFilePath text;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS netFilePath text;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS startSeconds decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS endSeconds decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS stepSeconds decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramAvgVehiclePerMinFromWestToEast decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramAvgVehiclePerMinFromSouthToNorth decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramVehicleDemandScalingFactor decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramAvgPedestrianPerMinFromWestToEast decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramAvgPedestrianPerMinFromSouthToNorth decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramPedestrianDemandScalingFactor decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramDemandScale decimal[];
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramMinGreenTimeSecWestEast decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramMaxGreenTimeSecWestEast decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramMinGreenTimeSecSouthNorth decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramMaxGreenTimeSecSouthNorth decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramPedestrianWaitThresholdSecNorthSouth decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramPedestrianWaitThresholdSecWestEast decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramVehicleQueueThresholdWestEast decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramVehicleQueueThresholdSouthNorth decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramPedestrianQueueThresholdNorthSouth decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramPedestrianQueueThresholdWestEast decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramStepSize decimal;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramRunTime integer;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramItersPerPar integer;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS paramTotalIterNum integer;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS laneAreaDetectorIds text[];
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS laneAreaDetectorLanes jsonb;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS laneAreaDetectorPaths text[];
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS e1DetectorIds text[];
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS e1DetectorLanes text[];
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS e1DetectorPaths text[];
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS walkingAreaIds text[];
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS walkingAreaLanes jsonb;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE TrafficSimulation ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS StorageBatteryDevice();
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS application jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS areaServed path;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS averageLife decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS batteryAssessmentMethods text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS batteryType text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS brandName text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS capacityCnnn jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS chargeDischargeReactivity decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS chargeEfficiency decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS chargePower decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS chargingModeAllowed jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS communication jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS dateLastReported text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS dimension jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS dischargeEfficiency decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS dischargePower decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS documentation text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS durationPeakPower decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS installationCondition jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS installationMode text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS lifeCycleNumber jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS manufacturerName text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS massEnergyDensity jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS maxOutputPower decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS maximumVoltageEOC decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS minimumVoltageEOD decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS modelName text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS nominalAmpere decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS nominalCapacity decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS nominalFrequency decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS nominalVoltage decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS operatingAltitude jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS operatingAmpere jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS operatingFrequency jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS operatingTemperature jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS operatingVoltage jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS overloadAccepted boolean;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS overloadAcceptedTime text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS peakPower decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS possibilityOfUse text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS protectionIK decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS protectionIP text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS rechargeEnergySource text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS refDevice jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS refPointOfInterest jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS roundTripEfficiency decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS seeAlso jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS selfDischargeRate decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS serialNumber text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS storableEnergy decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS toolBMS boolean;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS typeEnergySource jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS typeOfUse text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS usableEnergy decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS volEnergyDensity jsonb;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS weight decimal;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE StorageBatteryDevice ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS TrafficFlowObserved();
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS entityId text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS trafficSimulationId text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS laneAreaDetectorId text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS sumocfgPath text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS customTrafficLightId text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS areaServed path;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS averageGapDistance decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS averageHeadwayTime decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS averageVehicleLength decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS averageVehicleSpeed decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS congested boolean;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS dateObserved text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS dateObservedFrom text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS dateObservedTo text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS intensity decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS laneDirection text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS laneId integer;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS occupancy decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS refRoadSegment text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS reversedLane boolean;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS seeAlso jsonb;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS vehicleSubType text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS vehicleType text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS customSigma decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS customAcceleration decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS customDeceleration decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS customMinGreenTime decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS customMaxGreenTime decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS customAverageVehiclesPerMinute decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS customDemandScalingFactor decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS customQueueLengthThreshold decimal;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE TrafficFlowObserved ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS SmartTrafficLight();
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS entityId text;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS smartTrafficLightName text;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS areaServed jsonb;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS routeIds text[];
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS routeIdNorth text;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS routeIdEast text;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS paramVehicleDemandScalingFactor decimal;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS paramStepSize decimal;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS paramRunTime integer;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS paramItersPerPar integer;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS paramTotalIterNum integer;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SmartTrafficLight ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS CrowdFlowObserved();
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS customTrafficLightId text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS trafficSimulationId text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS entityId text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS walkingAreaId text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS areaServed polygon;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS averageCrowdSpeed decimal;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS averageHeadwayTime decimal;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS congested boolean;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS dateObserved text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS dateObservedFrom text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS dateObservedTo text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS direction text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS occupancy decimal;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS peopleCount integer;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS refRoadSegment jsonb;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS seeAlso jsonb;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE CrowdFlowObserved ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS ParkingAccess();
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS areaServed polygon;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS category jsonb;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS features jsonb;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS height decimal;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS location path;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS refOffStreetParking jsonb;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS seeAlso jsonb;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS slope decimal;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS width decimal;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE ParkingAccess ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS PhotovoltaicMeasurement();
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS activePower decimal;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS areaServed path;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS current decimal;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS dateEnergyMeteringStarted text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS dateObserved text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS dateObservedFrom text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS dateObservedTo text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS inverterStatus jsonb;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS nominalPeakPowerGeneration decimal;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS reactivePower decimal;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS refPhotovoltaicDevice jsonb;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS refPointOfInterest jsonb;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS seeAlso jsonb;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS temperature decimal;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE PhotovoltaicMeasurement ADD COLUMN IF NOT EXISTS userKey bigint;
