DROP TABLE CrowdFlowObserved CASCADE;
DROP TABLE TrafficSimulation CASCADE;
DROP TABLE SimulationReport CASCADE;
DROP TABLE SmartTrafficLight CASCADE;
DROP TABLE ParkingAccess CASCADE;
DROP TABLE TrafficFlowObserved CASCADE;
DROP TABLE SiteUser CASCADE;
